# Generated by Django 5.2.1 on 2025-06-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание (опционально)')),
                ('salary_graph', models.ImageField(upload_to='charts/', verbose_name='График зарплат по годам')),
                ('vacancy_graph', models.ImageField(upload_to='charts/', verbose_name='График количества вакансий по годам')),
                ('salary_table', models.TextField(verbose_name='HTML-таблица зарплат по годам')),
                ('vacancy_table', models.TextField(verbose_name='HTML-таблица количества вакансий по годам')),
            ],
            options={
                'verbose_name': 'Общая статистика',
                'verbose_name_plural': 'Общая статистика',
            },
        ),
    ]
