# Generated by Django 5.2.1 on 2025-06-01 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession_name', models.CharField(default='iOS-разработчик', max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='main_images/')),
            ],
        ),
    ]
