# Generated by Django 5.2.1 on 2025-06-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_generalstatistics_salary_graph_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Востребованность iOS-разработчика', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('ios_salary_level_trend', models.ImageField(upload_to='charts/', verbose_name='Динамика уровня зарплат по годам для выбранной профессии')),
                ('ios_vacancies_level_trend', models.ImageField(upload_to='charts/', verbose_name='Динамика количества вакансий по годам для выбранной профессии')),
            ],
            options={
                'verbose_name': 'Востребованность',
                'verbose_name_plural': 'Востребованность',
            },
        ),
    ]
