# Generated by Django 5.2.1 on 2025-06-01 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_demandstatistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='География iOS-разработчика', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('geo_ios_city_salary', models.ImageField(upload_to='charts/', verbose_name='Уровень зарплат по городам для выбранной профессии')),
                ('geo_ios_city_vacancy_share', models.ImageField(upload_to='charts/', verbose_name='Доля вакансий по городам для выбранной профессии')),
            ],
            options={
                'verbose_name': 'География',
                'verbose_name_plural': 'География',
            },
        ),
    ]
