# Generated by Django 5.2.1 on 2025-06-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_geostatistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillsStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='ТОП-20 навыков для iOS-разработчика', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('skills_top_ios_trend', models.ImageField(upload_to='charts/', verbose_name='ТОП-20 навыков по годам для выбранной профессии')),
            ],
            options={
                'verbose_name': 'Навыки',
                'verbose_name_plural': 'Навыки',
            },
        ),
    ]
