# Generated by Django 5.2.1 on 2025-06-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_skillsstatistics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainpageinfo',
            old_name='description',
            new_name='greeting_description',
        ),
        migrations.RenameField(
            model_name='mainpageinfo',
            old_name='image',
            new_name='greeting_img',
        ),
        migrations.AddField(
            model_name='mainpageinfo',
            name='additional_img',
            field=models.ImageField(default='', upload_to='main_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainpageinfo',
            name='additional_info',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainpageinfo',
            name='additional_info_name',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainpageinfo',
            name='header_1',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainpageinfo',
            name='under_1_1',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainpageinfo',
            name='under_1_2',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainpageinfo',
            name='under_1_3',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainpageinfo',
            name='under_1_4',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainpageinfo',
            name='under_2_1',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainpageinfo',
            name='under_2_2',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainpageinfo',
            name='under_2_3',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainpageinfo',
            name='under_3_1',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainpageinfo',
            name='under_3_2',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainpageinfo',
            name='under_3_3',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainpageinfo',
            name='under_4_1',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainpageinfo',
            name='under_4_2',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainpageinfo',
            name='under_4_3',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainpageinfo',
            name='under_header_1',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainpageinfo',
            name='under_header_2',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainpageinfo',
            name='under_header_3',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainpageinfo',
            name='under_header_4',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mainpageinfo',
            name='profession_name',
            field=models.CharField(),
        ),
    ]
