# Generated by Django 5.2.1 on 2025-06-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_description_mainpageinfo_greeting_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpageinfo',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
