# Generated by Django 5.2.1 on 2025-06-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_mainpageinfo_additional_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='HHStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=310)),
                ('skills_str', models.CharField()),
                ('company', models.CharField()),
                ('salary', models.CharField()),
                ('area', models.CharField()),
                ('published_at', models.DateField()),
            ],
        ),
    ]
