# Generated by Django 5.2.1 on 2025-06-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_hhstatistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalstatistics',
            name='salary_by_city_csv',
            field=models.FileField(blank=True, null=True, upload_to='csv/', verbose_name='CSV: Зарплаты по городам'),
        ),
        migrations.AddField(
            model_name='generalstatistics',
            name='salary_dynamics_csv',
            field=models.FileField(blank=True, null=True, upload_to='csv/', verbose_name='CSV: Динамика зарплат'),
        ),
        migrations.AddField(
            model_name='generalstatistics',
            name='top_skills_csv',
            field=models.FileField(blank=True, null=True, upload_to='csv/', verbose_name='CSV: ТОП-20 навыков'),
        ),
        migrations.AddField(
            model_name='generalstatistics',
            name='vacancies_dynamics_csv',
            field=models.FileField(blank=True, null=True, upload_to='csv/', verbose_name='CSV: Динамика вакансий'),
        ),
        migrations.AddField(
            model_name='generalstatistics',
            name='vacancies_share_by_city_csv',
            field=models.FileField(blank=True, null=True, upload_to='csv/', verbose_name='CSV: Доля вакансий по городам'),
        ),
    ]
