# Generated by Django 5.2.1 on 2025-06-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_generalstatistics_salary_by_city_csv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillsstatistics',
            name='skills_top_ios_trend_csv',
            field=models.FileField(blank=True, null=True, upload_to='csv/', verbose_name='CSV: ТОП-20 навыков по годам для выбранной профессии'),
        ),
    ]
