# Generated by Django 5.2.1 on 2025-06-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_geostatistics_geo_ios_city_salary_csv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandstatistics',
            name='ios_salary_level_trend_csv',
            field=models.FileField(blank=True, null=True, upload_to='csv/', verbose_name='CSV: Динамика уровня зарплат по годам для выбранной профессии'),
        ),
        migrations.AddField(
            model_name='demandstatistics',
            name='ios_vacancies_level_trend_csv',
            field=models.FileField(blank=True, null=True, upload_to='csv/', verbose_name='CSV: Динамика количества вакансий по годам для выбранной профессии'),
        ),
    ]
