# Generated by Django 5.2.1 on 2025-06-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_demandstatistics_ios_salary_level_trend_csv_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hhstatistics',
            name='published_at',
            field=models.DateTimeField(),
        ),
    ]
