# Generated by Django 5.2.1 on 2025-06-18 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_hhstatistics_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalstatistics',
            name='ending',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (опционально)'),
        ),
        migrations.AddField(
            model_name='generalstatistics',
            name='under_1',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalstatistics',
            name='under_2',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalstatistics',
            name='under_3',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalstatistics',
            name='under_4',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalstatistics',
            name='under_5',
            field=models.CharField(blank=True, null=True),
        ),
    ]
