# Generated by Django 5.2.1 on 2025-06-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_generalstatistics_ending_generalstatistics_under_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandstatistics',
            name='ending',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (опционально)'),
        ),
        migrations.AddField(
            model_name='demandstatistics',
            name='under_1',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandstatistics',
            name='under_2',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geostatistics',
            name='ending',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (опционально)'),
        ),
        migrations.AddField(
            model_name='geostatistics',
            name='under_1',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geostatistics',
            name='under_2',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skillsstatistics',
            name='ending',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (опционально)'),
        ),
        migrations.AddField(
            model_name='skillsstatistics',
            name='under_1',
            field=models.CharField(blank=True, null=True),
        ),
    ]
