# Generated by Django 5.2.1 on 2025-06-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_demandstatistics_ending_demandstatistics_under_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hhstatistics',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
